#!/bin/bash
cd "$(dirname "$0")"
echo "Please type application name: "
read APP_NAME
mkdir -p "$APP_NAME.app/Contents/Resources"
mkdir -p "$APP_NAME.app/Contents/MacOS"
cp ./icon.icns "$APP_NAME.app/Contents/Resources/$APP_NAME.icns"
cp ./run "$APP_NAME.app/Contents/MacOS/$APP_NAME"
cp -R ./bin "$APP_NAME.app/Contents/MacOS/bin/"
./setfileicon "$APP_NAME.app/Contents/Resources/$APP_NAME.icns" "$APP_NAME.app" 
